### ISSUE TITLE
Det kan ikke søges på medlemmer Martin

### ISSUE THREAD

**Issue by Joghur** [cph-mn521/Delfinen#2]
Som titel

**Comment by Joghur** [comment]
Når man søger på Niels Bang:

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at delfinen.Controller.search(Controller.java:180)

**Comment by Joghur** [comment]
Det er når Konkurrencesvømmer er valgt

**Comment by nfmbang** [comment]
fixed
